POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
   "email":"test@test.com",
   "username":"aurele",
   "phone":"0625252525",
   "password":"azerty"
}
###

POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"azerty"
}